// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package futuresmocks

import (
	"context"

	"github.com/shrtyk/kv-store/internal/core/ports/futures"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFuturesStore creates a new instance of MockFuturesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFuturesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFuturesStore {
	mock := &MockFuturesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFuturesStore is an autogenerated mock type for the FuturesStore type
type MockFuturesStore struct {
	mock.Mock
}

type MockFuturesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFuturesStore) EXPECT() *MockFuturesStore_Expecter {
	return &MockFuturesStore_Expecter{mock: &_m.Mock}
}

// Fulfill provides a mock function for the type MockFuturesStore
func (_mock *MockFuturesStore) Fulfill(logIndex int64) {
	_mock.Called(logIndex)
	return
}

// MockFuturesStore_Fulfill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fulfill'
type MockFuturesStore_Fulfill_Call struct {
	*mock.Call
}

// Fulfill is a helper method to define mock.On call
//   - logIndex int64
func (_e *MockFuturesStore_Expecter) Fulfill(logIndex interface{}) *MockFuturesStore_Fulfill_Call {
	return &MockFuturesStore_Fulfill_Call{Call: _e.mock.On("Fulfill", logIndex)}
}

func (_c *MockFuturesStore_Fulfill_Call) Run(run func(logIndex int64)) *MockFuturesStore_Fulfill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFuturesStore_Fulfill_Call) Return() *MockFuturesStore_Fulfill_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFuturesStore_Fulfill_Call) RunAndReturn(run func(logIndex int64)) *MockFuturesStore_Fulfill_Call {
	_c.Run(run)
	return _c
}

// NewFuture provides a mock function for the type MockFuturesStore
func (_mock *MockFuturesStore) NewFuture(logIndex int64) futures.Future {
	ret := _mock.Called(logIndex)

	if len(ret) == 0 {
		panic("no return value specified for NewFuture")
	}

	var r0 futures.Future
	if returnFunc, ok := ret.Get(0).(func(int64) futures.Future); ok {
		r0 = returnFunc(logIndex)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(futures.Future)
		}
	}
	return r0
}

// MockFuturesStore_NewFuture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewFuture'
type MockFuturesStore_NewFuture_Call struct {
	*mock.Call
}

// NewFuture is a helper method to define mock.On call
//   - logIndex int64
func (_e *MockFuturesStore_Expecter) NewFuture(logIndex interface{}) *MockFuturesStore_NewFuture_Call {
	return &MockFuturesStore_NewFuture_Call{Call: _e.mock.On("NewFuture", logIndex)}
}

func (_c *MockFuturesStore_NewFuture_Call) Run(run func(logIndex int64)) *MockFuturesStore_NewFuture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFuturesStore_NewFuture_Call) Return(future futures.Future) *MockFuturesStore_NewFuture_Call {
	_c.Call.Return(future)
	return _c
}

func (_c *MockFuturesStore_NewFuture_Call) RunAndReturn(run func(logIndex int64) futures.Future) *MockFuturesStore_NewFuture_Call {
	_c.Call.Return(run)
	return _c
}

// StartGC provides a mock function for the type MockFuturesStore
func (_mock *MockFuturesStore) StartGC(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockFuturesStore_StartGC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartGC'
type MockFuturesStore_StartGC_Call struct {
	*mock.Call
}

// StartGC is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFuturesStore_Expecter) StartGC(ctx interface{}) *MockFuturesStore_StartGC_Call {
	return &MockFuturesStore_StartGC_Call{Call: _e.mock.On("StartGC", ctx)}
}

func (_c *MockFuturesStore_StartGC_Call) Run(run func(ctx context.Context)) *MockFuturesStore_StartGC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFuturesStore_StartGC_Call) Return() *MockFuturesStore_StartGC_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFuturesStore_StartGC_Call) RunAndReturn(run func(ctx context.Context)) *MockFuturesStore_StartGC_Call {
	_c.Run(run)
	return _c
}

// NewMockFuture creates a new instance of MockFuture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFuture(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFuture {
	mock := &MockFuture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFuture is an autogenerated mock type for the Future type
type MockFuture struct {
	mock.Mock
}

type MockFuture_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFuture) EXPECT() *MockFuture_Expecter {
	return &MockFuture_Expecter{mock: &_m.Mock}
}

// Wait provides a mock function for the type MockFuture
func (_mock *MockFuture) Wait(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFuture_Wait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Wait'
type MockFuture_Wait_Call struct {
	*mock.Call
}

// Wait is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockFuture_Expecter) Wait(ctx interface{}) *MockFuture_Wait_Call {
	return &MockFuture_Wait_Call{Call: _e.mock.On("Wait", ctx)}
}

func (_c *MockFuture_Wait_Call) Run(run func(ctx context.Context)) *MockFuture_Wait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFuture_Wait_Call) Return(err error) *MockFuture_Wait_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFuture_Wait_Call) RunAndReturn(run func(ctx context.Context) error) *MockFuture_Wait_Call {
	_c.Call.Return(run)
	return _c
}
